seed: 42
device: cuda:0
num_steps_per_env: 24
init_at_random_ep_len: true
max_iterations: 8000
empirical_normalization: {}
obs_groups:
  actor:
  - policy
  critic:
  - critic
clip_actions: null
check_for_nan: true
save_interval: 50
experiment_name: rough_direct
run_name: ''
logger: wandb
neptune_project: basic-locomotion
wandb_project: basic-locomotion
resume: false
load_run: .*
load_checkpoint: model_.*.pt
class_name: OnPolicyRunner
actor:
  class_name: MLPModel
  hidden_dims:
  - 256
  - 256
  - 256
  activation: elu
  obs_normalization: false
  distribution_cfg:
    class_name: GaussianDistribution
    init_std: 1.0
    std_type: scalar
critic:
  class_name: MLPModel
  hidden_dims:
  - 512
  - 256
  - 128
  activation: elu
  obs_normalization: false
  distribution_cfg: null
algorithm:
  class_name: PPO
  num_learning_epochs: 5
  num_mini_batches: 4
  learning_rate: 0.001
  schedule: adaptive
  gamma: 0.97
  lam: 0.99
  entropy_coef: 0.005
  desired_kl: 0.01
  max_grad_norm: 1.0
  optimizer: adam
  value_loss_coef: 1.0
  use_clipped_value_loss: true
  clip_param: 0.15
  normalize_advantage_per_mini_batch: false
  share_cnn_encoders: false
  rnd_cfg: null
  symmetry_cfg: null
policy: {}
dataset:
  amp_data_path: /home/gturrisi/isaaclab_ws_home/basic-locomotion-isaaclab/scripts/amp_rl/amp_dataset
  datasets:
    flat: 1.0
    boxes: 1.0
    stairs: 1.0
  slow_down_factor: 1.0
  amp_joint_names:
  - FL_hip_joint
  - FR_hip_joint
  - RL_hip_joint
  - RR_hip_joint
  - FL_thigh_joint
  - FR_thigh_joint
  - RL_thigh_joint
  - RR_thigh_joint
  - FL_calf_joint
  - FR_calf_joint
  - RL_calf_joint
  - RR_calf_joint
  velocity_representation: body_fixed
discriminator:
  class_name: Discriminator
  hidden_dims:
  - 512
  - 256
  reward_scale: 1.0
  loss_type: BCEWithLogits
  empirical_normalization: false
morphologycal_symmetries_cfg:
  class_name: MorphologycalSymmetries
  obs_space_names_actor:
  - base_lin_vel
  - base_ang_vel
  - gravity
  - des_base_lin_vel_xy
  - des_base_ang_vel_yaw
  - joints_pos
  - joints_vel
  - joints_pos
  - clock_data
  - base_lin_vel
  - base_ang_vel
  - gravity
  - des_base_lin_vel_xy
  - des_base_ang_vel_yaw
  - joints_pos
  - joints_vel
  - joints_pos
  - clock_data
  - base_lin_vel
  - base_ang_vel
  - gravity
  - des_base_lin_vel_xy
  - des_base_ang_vel_yaw
  - joints_pos
  - joints_vel
  - joints_pos
  - clock_data
  - base_lin_vel
  - base_ang_vel
  - gravity
  - des_base_lin_vel_xy
  - des_base_ang_vel_yaw
  - joints_pos
  - joints_vel
  - joints_pos
  - clock_data
  - base_lin_vel
  - base_ang_vel
  - gravity
  - des_base_lin_vel_xy
  - des_base_ang_vel_yaw
  - joints_pos
  - joints_vel
  - joints_pos
  - clock_data
  - heightmap:7x9
  obs_space_names_critic:
  - base_lin_vel
  - base_ang_vel
  - gravity
  - des_base_lin_vel_xy
  - des_base_ang_vel_yaw
  - joints_pos
  - joints_vel
  - joints_pos
  - clock_data
  - base_lin_vel
  - base_ang_vel
  - gravity
  - des_base_lin_vel_xy
  - des_base_ang_vel_yaw
  - joints_pos
  - joints_vel
  - joints_pos
  - clock_data
  - base_lin_vel
  - base_ang_vel
  - gravity
  - des_base_lin_vel_xy
  - des_base_ang_vel_yaw
  - joints_pos
  - joints_vel
  - joints_pos
  - clock_data
  - base_lin_vel
  - base_ang_vel
  - gravity
  - des_base_lin_vel_xy
  - des_base_ang_vel_yaw
  - joints_pos
  - joints_vel
  - joints_pos
  - clock_data
  - base_lin_vel
  - base_ang_vel
  - gravity
  - des_base_lin_vel_xy
  - des_base_ang_vel_yaw
  - joints_pos
  - joints_vel
  - joints_pos
  - clock_data
  - heightmap:7x9
  - clock_data
  - clock_data
  - clock_data
  - clock_data
  - clock_data
  - clock_data
  - base_lin_vel
  - invariant_scalar
  - invariant_scalar
  - clock_data
  - clock_data
  - clock_data
  - clock_data
  - heightmap:4x4
  action_space_names:
  - joints_pos
  joints_order:
  - FL_hip_joint
  - FR_hip_joint
  - RL_hip_joint
  - RR_hip_joint
  - FL_thigh_joint
  - FR_thigh_joint
  - RL_thigh_joint
  - RR_thigh_joint
  - FL_calf_joint
  - FR_calf_joint
  - RL_calf_joint
  - RR_calf_joint
  robot_name: a1
  state_dependent_std: false
  small_init_output: true
  symmetric_initialization: true
  use_data_augmentation: false
