#include "dls_annotation.idl"

module dls2_interfaces {
  module msg {
	@Robot
	struct DesiredTorques
	{
		// Header
		string frame_id;
		unsigned long sequence_id;
		double timestamp;

		//data
		@JointState sequence<double> desired_torques;
	};
  };
};
